version: 2

sources:
  - name: erp
    description: Banco réplica do erp da northwind.
    schema: desafiodw
    tables:
      - name: address
        description: Endereços.
        columns:
          - name: addressid
            description: Chave primária.
            tests:
              - unique
              - not_null
      - name: businessentityaddress
        columns:
          - name: businessentityid
            description: Chave primária.
            tests:
              - unique
              - not_null      
      - name: countryregion
        columns:
          - name: countryregioncode
            description: Chave primária.
            tests:
              - unique
              - not_null       
      - name: creditcard
        columns:
          - name: creditcardid
            description: Chave primária.
            tests:
              - unique
              - not_null      
      - name: person
        columns:
          - name: businessentityid
            description: Chave primária.
            tests:
              - unique
              - not_null      
      - name: personcreditcard
        columns:
          - name: businessentityid
            description: Chave primária.
            tests:
              - unique
              - not_null        
      - name: product
        columns:
          - name: productid     
            description: Chave primária.
            tests:
              - unique
              - not_null       
      - name: salesorderdetail
        columns:
          - name: salesorderdetailid
            description: Chave primária.
            tests:
              - unique
              - not_null
      - name: salesorderheader
        columns:
          - name: salesorderid
            description: Chave primária.
            tests:
              - unique
              - not_null
      - name: salesorderheadersalesreason
        columns:
          - name: salesreasonid
            description: Chave primária.
            tests:
              - unique
              - not_null
      - name: salesreason
        columns:
          - name: salesreasonid
            description: Chave primária.
            tests:
              - unique
              - not_null
      - name: salesterritory
        columns:
          - name: territoryid
            description: Chave primária.
            tests:
              - unique
              - not_null
      - name: stateprovince
        columns:
          - name: stateprovinceid
            description: Chave primária.
            tests:
              - unique
              - not_null