version: 2

sources:
  - name: erp
    description: Banco réplica do erp da northwind.
    schema: Adventure_Works
    tables:
      - name: Address
        description: Endereços.
        columns:
          - name: addressid
            description: Chave primária.
            tests:
              - unique
              - not_null
          - name: stateprovinceid
          - name: city
            description: Cidade.
          - name: addressline2
          - name: modifieddate
          - name: rowguid
          - name: _sdc_table_version
          - name: postalcode
          - name: spatiallocation
          - name: _sdc_received_at
          - name: _sdc_sequence
          - name: addressline1
          - name: _sdc_batched_at            
      - name: businessentityaddress 
      - name: countryregion
      - name: creditcard
      - name: person
      - name: personcreditcard
      - name: product
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: salesterritory
      - name: stateprovince